volumes:
  # vault-data:
  shared-secret:
    external: true

networks:
  net_api:
    external: true
  proxy-net:
    external: true

services:
  vault:
    image: lambops/vault:secure
    container_name: HASHICORP-VAULT
    hostname: vault.infra.docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-s", "http://vault.infra.docker:8200/v1/sys/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        vault server -config=/vault/config/vault-server-config.hcl & \
        while ! curl  --silent --max-time 90 http://172.28.0.6:8200/v1/sys/health; do \
          echo 'Waiting for Vault to be ready...'; \
          sleep 20; \
        done && \
        echo 'Vault is ready!' && \
        echo 'Lancement du script Vault init' && \
        sh /vault/vault-init.sh && \
        if [ $? != 0 ]; then
          echo 'Initialisation mal terminée ' && \
          exit 1
        fi
        sh /vault/vault-auth.sh && \
        vault agent -config=/vault/config/vault-agent-config.hcl & \
        tail -f /dev/null"
    expose:
      - "8200"
    environment:
      VAULT_ADDR: "https://vault.infra.docker:8200"
      VAULT_API_ADDR: "https://vault.infra.docker:8200"
      VAULT_USER: vault
      VAULT_CACERT: "/opt/vault/tls/vault-ca.crt"
    cap_add:
      - IPC_LOCK
    volumes:
      - shared-secret:/vault/shared
      - ./vault-data:/vault/data
      - ./vault-config:/vault/config
      - ./vault-init.sh:/vault/vault-init.sh
      - ./vault-auth.sh:/vault/vault-auth.sh
      - ./Certs:/opt/vault/tls
    extra_hosts:
      - "consul.infra.docker:172.28.0.3"
      - "proxy.infra.docker:172.21.0.3"
    depends_on:
      - consul
    networks:
      net_api:
        ipv4_address: 172.28.0.6
      proxy-net:

  consul:
    image: lambops/consul:secure
    container_name: HASHICORP-CONSUL
    hostname: consul.infra.docker
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-s", "http://172.28.0.3:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - "8500"
      - "8501"
    environment:
      CONSUL_CACERT: /opt/consul/tls/vault-ca.crt
    volumes:
      - ./Certs:/opt/consul/tls
      - ./vault-config/consul-server-config.hcl:/consul/config/consul-server-config.hcl
    command: >
      sh -c  "
        consul agent -config-file=/consul/config/consul-server-config.hcl & \
        tail -f /dev/null"
    extra_hosts:
      - "vault.infra.docker:172.28.0.6"
      - "proxy.infra.docker:172.21.0.3"
    networks:
      net_api:
        ipv4_address: 172.28.0.3
      proxy-net:
