version: '3.3'
services:
  authentication:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$DOCKER_TAG
    container_name: dev-$CI_PROJECT_NAME
    ports:
      - "8081:8081"
    networks:
      - net_api
    volumes:
      -  /etc/ssl/certs/localhost.pfx:/etc/ssl/certs/localhost.pfx
      - ./Redis/certs/redis-client.pfx:/etc/ssl/certs/redis-client.pfx 
      - ./Redis/certs/ca.crt:/etc/ssl/certs/ca.crt
      - ./appsettings.json:/app/appsettings.Development.json
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CERT_PASSWORD
networks:
  net_api:
    external: true