version: '3.3'
services:
  web-interface:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$DOCKER_TAG
    container_name: dev-$CI_PROJECT_NAME
    ports:
      - "8084:8084"
    networks:
      - net_api
    volumes:
      -  /etc/ssl/certs/localhost.pfx:/etc/ssl/certs/localhost.pfx # Certificat pour le serveur en variable d'environnement
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CERT_PASSWORD
networks:
  net_api:
    external: true