version: '3.9'
volumes:
  data:
networks:
  net_api:
    external: true
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RABBITMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      net_api:
        ipv4_address: 172.28.0.5
    volumes:
      - ./data:/data
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: always

