networks:
   net_api:
    external: true

volumes:
  prometheus-data:
  grafana-data:

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.95.0
    container_name: OPEN-TELEMETRY
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./Config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
    networks:
      net_api:
        ipv4_address: 172.28.0.13
  prometheus:
    image: prom/prometheus:latest
    container_name: PROMETHEUS
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./Config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      net_api:
        ipv4_address: 172.28.0.14

  grafana:
    image: lambops/grafana-ent:secure
    container_name: GRAFANA
    ports:
      - '3000:3000'
    environment:
    - GF_SERVER_ROOT_URL=https://develop.lamboft.it/grafana # Pas l'ip du container mais le nom de domaine
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      net_api:
        ipv4_address: 172.28.0.15

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: NODE-EXPORTER
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      net_api:
        ipv4_address: 172.28.0.16
