version: "3.9"
services:
  hashicorp-vault:
    image: hashicorp/vault:1.18
    container_name: HASHICORP-VAULT
    command: >
      sh -c "
        apk add --no-cache --upgrade bash && \
        apk add --update curl && \
        rm -rf /var/cache/apk/* && \
        chmod +x /vault-init.sh && \
        vault server -config=/vault/config/vault-server-config.hcl & \
        while ! curl --silent --max-time 60 http://172.28.0.6:8200/v1/sys/health; do \
          echo 'Waiting for Vault to be ready...'; \
          sleep 20; \
        done && \
        echo 'Vault is ready!' && \
        echo 'Lancement du script Vault init' && \
        chmod -R 755 /vault && \
        sh /vault-init.sh && \
        if [ $? != 0 ]; then
          echo 'Initialisation mal terminée ' && \
          exit 1
        fi
        chmod +x /vault-auth.sh && \
        sh /vault-auth.sh && \
        vault agent -config=/vault/config/vault-agent-config.hcl & \
        tail -f /dev/null"
    ports:
      - "8200:8200"
    networks:
      net_api:
        ipv4_address: 172.28.0.6
    environment:
      VAULT_ADDR: "http://172.28.0.6:8200"
      VAULT_API_ADDR: "http://172.28.0.6:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data
      - ./vault-init.sh:/vault-init.sh # Unseal Vault et init
      - ./vault-auth.sh:/vault-auth.sh # Authentification via approle
      - ./vault-config:/vault/config
      - /tmp/vault-token:/tmp

    depends_on:
      - hashicorp-consul

  hashicorp-consul:
    image: hashicorp/consul:1.18
    container_name: CONSUL-VAULT-STORAGE
    ports:
      - "8500:8500"
    networks:
      net_api:
        ipv4_address: 172.28.0.3
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - data-consul:/consul/data

volumes:
  data-consul:
  vault-data:

networks:
  net_api:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    external: true
