version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: MYSQL
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=gravitee
      - MYSQL_USER=gravitee_user
      - MYSQL_PASSWORD=gravitee_password
    ports:
      - "3306:3306"
    networks:
      vault_net:
        ipv4_address: 172.19.0.10

  gateway:
    image: graviteeio/apim-gateway:4.2.0
    container_name: GRAVITEE-GATEWAY
    ports:
      - "8092:8082"
      - "8093:8083"
    networks:
      vault_net:
        ipv4_address: 172.19.0.5
    environment:
      - gravitee_management_mysql_uri=jdbc:mysql://mysql:3306/gravitee
      - gravitee_analytics_type=jdbc
      - gravitee_analytics_mysql_uri=jdbc:mysql://mysql:3306/gravitee_analytics
    volumes:
      -  ./gravitee.yml:/opt/graviteeio-gateway/config/gravitee.yml

  management-api:
    image: graviteeio/apim-management-api:4.2.0
    container_name: GRAVITEE-MANAGEMENT-API
    ports:
      - "8094:8084"
    networks:
      vault_net:
        ipv4_address: 172.19.0.4
    environment:
      - gravitee_management_mysql_uri=jdbc:mysql://mysql:3306/gravitee
      - gravitee_analytics_type=jdbc
      - gravitee_analytics_mysql_uri=jdbc:mysql://mysql:3306/gravitee_analytics
      - gravitee_jwt_secret=prAtakbkFBUFu1hcTi/ZctqLJ7Ssn5hCcGcS+/2+Xpo

  management-ui:
    image: graviteeio/apim-management-ui:4.2.0
    container_name: GRAVITEE-MANAGEMENT-UI
    depends_on:
      - management-api
    ports:
      - "8090:80"
    networks:
      vault_net:
        ipv4_address: 172.19.0.7

  portal-ui:
    image: graviteeio/apim-portal-ui:4.2.0
    container_name: GRAVITEE-PORTAL-UI
    depends_on:
      - management-api
    ports:
      - "8091:80"
    networks:
      vault_net:
        ipv4_address: 172.19.0.8

volumes:
  mysql_data:

networks:
  vault_net:
    external: true
