version: "3"
services:
  postgres:
    image: postgres:17
    container_name: POSTGRESQL
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonar_lamboft_services
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 172.26.0.4 

  sonarqube:
    image: sonarqube:community
    container_name: SONARQUBE
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres/sonar_lamboft_services
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
      SONAR_WEB_CONTEXT: /sonarqube

    hostname: sonarqube.local
    networks:
      net:
        ipv4_address: 172.26.0.5  # Exemple d'adresse IP statique

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16  # Sous-réseau que tu as trouvé
volumes:
  sonar_db_data:
