#
# ╔══════════════════════════════════════════════════╗
# ║Section Management : db connect                   ║
# ║ - Authentification activated                     ║
# ║ - Enabled SSL/TLS                                ║
# ╚══════════════════════════════════════════════════╝
management:
  type: mongodb
  mongodb:
    dbname: ${ds.mongodb.dbname} 
    host: ${ds.mongodb.host} 
    port: ${ds.mongodb.port}
    username: ${ds.mongodb.username}
    password: ${ds.mongodb.password}
    authSource: ${ds.mongodb.authenticationDatabase}
    sslEnabled: true
    sslInvalidHostNameAllowed: false
    # truststore:
    #   path: /path/to/truststore.jks
    #   type: jks
    #   password: changeit
