# ╔══════════════════════════════════════════════════╗
# ║Section Plugins  :                                ║
# ║ - Enabled plugins                                ║
# ╚══════════════════════════════════════════════════╝
plugins:
  enabled: true
  pluginFolder: /opt/gravitee-mgnt/plugins
