# ╔══════════════════════════════════════════════════╗
# ║Section export gravitee analytics  :              ║
# ║ - Enabled                                        ║
# ╚══════════════════════════════════════════════════╝
analytics-export:
  rabbitmq:
    brokers:
      - rabbitmq:9092
    topic: gravitee-all-analytics
