# ╔══════════════════════════════════════════════════╗
# ║Section Clustering  :                             ║
# ║ - Enabled plugins                                ║
# ╚══════════════════════════════════════════════════╝
deployment:
  mode: clustered
  nodeId: node-01
