version: '3.3'
networks:
  net_api:
    external: true
services:
  redis:
    image: redis:latest
    container_name: REDIS-SECURE
    ports:
     - "6379:6379"  # Expose Redis seulement si nécessaire
    networks:
      net_api:
        ipv4_address: 172.28.0.2
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./certs:/certs
      - /etc/localtime:/etc/localtime:ro
      - ./redis-log:/var/log/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "1"
    tty: true
