services:
  hashicorp-vault:
    image: hashicorp/vault:1.17.5
    container_name: HASHICORP-VAULT
    command: >
      sh -c "
        apk add --no-cache --upgrade bash && \
        apk add --update curl && \
        rm -rf /var/cache/apk/*
        ls -l && \
        chmod +x /vault-init.sh && \
        cat /vault-init.sh && \
        vault server -config=/vault/config/vault.hcl & \
        while ! curl --silent http://172.28.0.6:8200/v1/sys/health; do \
          echo 'Waiting for Vault to be ready...'; \
          sleep 20; \
        done && \
        echo 'Lancement du script Vault init ' && \
        sh /vault-init.sh && \
        echo 'Vault is ready to be use! His persistence data can be found in consul-data' && \ 
        tail -f /dev/null"
    ports:
     - "8200:8200"
    networks:
      net_api:
        ipv4_address: 172.28.0.6
    environment:
      VAULT_ADDR: "http://172.28.0.6:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data  # Stockage persistant pour Vault
      - ./vault-init.sh:/vault-init.sh  # Script d'initialisation de Vault
      - ./vault-config:/vault/config  # Montée du répertoire de configuration
    depends_on:
      - hashicorp-consul

  hashicorp-consul:
    image: hashicorp/consul:1.17
    container_name: CONSUL-VAULT-STORAGE
    command: "agent -dev -client=0.0.0.0"
    ports:
     - "8500:8500"
    networks:
      net_api:
        ipv4_address: 172.28.0.3
    volumes:
      - consul-data:/consul/data


volumes:
  consul-data:
  vault-data:
networks:
 net_api:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    external: true
