version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RABBITMQ
    ports:
      - "5672:5672"     # Port pour les connexions des clients
      - "15672:15672"   # Port pour l'interface graphique
    volumes:
      - ./data:/data
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}  # Utilisateur par défaut
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}  # Mot de passe par défaut
    restart: always
volumes:
  data:
