volumes:
  vault-data:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16

services:
  vault:
    image: lambops/vault:secure
    container_name: HASHICORP-VAULT
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-s", "http://172.26.0.6:8200/v1/sys/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
        vault server -config=/vault/config/vault-server-config.hcl & \
        while ! curl  --silent --max-time 90 http://172.26.0.6:8200/v1/sys/health; do \
          echo 'Waiting for Vault to be ready...'; \
          sleep 20; \
        done && \
        echo 'Vault is ready!' && \
        echo 'Lancement du script Vault init' && \
        sh /vault/vault-init.sh && \
        if [ $? != 0 ]; then
          echo 'Initialisation mal terminée ' && \
          exit 1
        fi
        sh /vault/vault-auth.sh && \
        vault agent -config=/vault/config/vault-agent-config.hcl & \
        tail -f /dev/null"
    ports:
      - "8200:8200"
    networks:
      net:
        ipv4_address: 172.26.0.6
    environment:
      VAULT_ADDR: "https://vault.infra.docker:8200"
      VAULT_API_ADDR: "https://vault.infra.docker:8200"
      VAULT_USER: vault
      VAULT_CACERT: "/opt/vault/tls/vault-ca.crt"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data
      - ./vault-config:/vault/config
      - /tmp/vault-token:/tmp
      - ./DockerBuilderFactory/Certs:/opt/vault/tls 
      - ./vault-init.sh:/vault/vault-init.sh
      - ./vault-auth.sh:/vault/vault-auth.sh
    extra_hosts:
      - "vault.infra.docker:172.26.0.6"
      - "consul.infra.docker:172.26.0.3"

    depends_on:
      - consul
  consul:
    image: lambops/consul:secure
    container_name: HASHICORP-CONSUL
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "curl", "-s", "http://172.26.0.3:8500/v1/status/leader"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8500:8500"
      - "8501:8501"
    environment:
      CONSUL_CACERT: /opt/consul/tls/vault-ca.crt
    volumes:
      - ./DockerBuilderFactory/Certs:/opt/consul/tls
      - ./vault-config/consul-server-config.hcl:/consul/consul-server-config.hcl
    command: >
      sh -c  "
        consul agent -config-file=/consul/config/consul-server-config.hcl & \
        tail -f /dev/null"
    extra_hosts:
      - "vault.infra.docker:172.26.0.6"
      - "consul.infra.docker:172.26.0.3"

    networks:
      net:
        ipv4_address: 172.26.0.3
  # health-watcher:
  #   build: ./health-watcher
  #   depends_on:
  #     web:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

