<?php
 /* If you are asked to put PLA in debug mode, this is how you do it: */
 $config->custom->debug['level'] = 2;
 $config->custom->debug['syslog'] = true;
 #  $config->custom->debug['file'] = '/tmp/pla_debug.log';

 $config->custom->jpeg['tmpdir'] = '/var/www/tmp';
/*
 * Autogenerated value will be automatically added by phpldapadmin/startup.sh
 */
$config->custom->session['blowfish'] = '_hFcSae!cmES<j3fIMVEk hvy@pF4P%s5mE34<=.(ww8oe}BU{x%Fk}yeRh=j3?';
$config->custom->appearance['hide_template_warning'] = true;
$config->custom->appearance['friendly_attrs'] = array(
        'facsimileTelephoneNumber' => 'Fax',
        'gid'                      => 'Group',
        'mail'                     => 'Email',
        'telephoneNumber'          => 'Telephone',
        'uid'                      => 'User Name',
        'userPassword'             => 'Password'
);


/*********************************************
 * Define your LDAP servers in this section  *
 *********************************************/

$servers = new Datastore();

/*
 * Autogenerated servers variables will come here
 */
$servers->newServer('ldap_pla');
$servers->setValue('server','host','ldap://openldap'); // nom du service docker
$servers->setValue('server','name','lamboft.it');

$servers->setValue('server','tls',false);
$servers->setValue('server', 'port', 389);

$servers->setValue('login','bind_id','cn=admin,dc=lamboft,dc=it');
$servers->setValue('login', 'bind_pass', '!!Art94721805&'); // encrypter

$servers->setValue('server', 'base', array('dc=lamboft,dc=it'));