volumes:
  pg_data:
networks:
  net_api:
    external: true
services:
  postgres:
    image: postgres:customize
    container_name: KEYCLOAK-POSTGRES-DB
    restart: always
    volumes:
        - pg_data:/var/lib/postgresql/data
        - ./.config.d/postgresql.conf:/etc/postgresql/postgresql.conf
        - ./.config.d/pg_hba.conf:/etc/postgresql/config.d/pg_hba.conf
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/config.d/pg_hba.conf"
    networks:
      net_api:
        ipv4_address: 172.28.0.33
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: KEYCLOAK
    restart: always
    volumes:
      - ./Certs/localhost.crt:/etc/x509/https/tls.crt
      - ./Certs/localhost.key:/etc/x509/https/tls.key
    healthcheck:
     test: ["CMD", "curl", "-k", "-f", "https://localhost:7443/health/ready"]
    command: [
      "start",
      "--https-port=7443",
      "--https-certificate-file=/etc/x509/https/tls.crt",
      "--https-certificate-key-file=/etc/x509/https/tls.key",
      "--http-enabled=false",
      ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db?sslmode=require
      KC_DB_USERNAME: keycloak_service
      KC_DB_PASSWORD: ${KC_DB_PASSWORD} 
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "7443:7443"
    depends_on:
      - postgres
    networks:
      net_api:
        ipv4_address: 172.28.0.32
  openldap:
    image: ldapauditlog:custom
    container_name: ANNUAIRE-OPEN-LDAP
    environment:
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ORGANISATION: ${LDAP_ORGANIZATION}  
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_ADMIN_USER: ${LDAP_ADMIN_USER}
      LDAP_TLS: "true"
    volumes:
      - ./openldap/ldap.log:/var/log/ldap-audit.log
    ports:
      - "664:664"                
    restart: unless-stopped
    networks:
      net_api:
        ipv4_address: 172.28.0.31

  phpldapadmin:
    image: osixia/phpldapadmin:stable
    container_name: PHP-OPENLDAP-IHM
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "true"

    restart: unless-stopped
    depends_on:
      - openldap
    networks:
      net_api:
        ipv4_address: 172.28.0.30
