volumes:
  pg_data:

networks:
  network:
    driver: bridge
services:
  postgres:
    image: postgres:custom
    container_name: KEYCLOAK-POSTGRES-DB
    restart: always
    volumes:
        - pg_data:/var/lib/postgresql/data
        - ./.config.d/postgresql.conf:/etc/postgresql/postgresql.conf
        - ./.config.d/pg_hba.conf:/etc/postgresql/config.d/pg_hba.conf
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/config.d/pg_hba.conf"
    networks:
      - network
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: KEYCLOAK
    restart: always
    volumes:
      - /etc/ssl/certs/localhost.crt:/etc/ssl/certs/localhost.crt  
      - /etc/ssl/private/localhost.key:/etc/ssl/private/localhost.key
    command: [
      "start-dev",
      "--https-certificate-file=/etc/ssl/certs/localhost.crt",
      "--https-certificate-key-file=/etc/ssl/private/localhost.key",
      "--https-port=8443", # quand on est en local
      "--hostname-strict=false" # quand on est en local
      # "--hostname-strict=true" # quand on est en prod
      # "--hostname=localhost" # quand on est en local
      # "--hostname=keycloak.example.com" # quand on est en prod
      # "--proxy=edge" # quand on est en local
      # "--proxy=passthrough" # quand on est en prod
      ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db?sslmode=require
      KC_DB_USERNAME: keycloak_service
      KC_DB_PASSWORD: Art437810 #${POSTGRES_PASSWORD:-4WXUms893U6j4GE&Hvk3S*hqcqebFgo!vZi} # htpasswd de apache
      # KC_HOSTNAME: localhost # l'enviornnement
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    networks:
      - network
  openldap:
    image: ldapauditlog:latest
    container_name: ANNUAIRE-OPEN-LDAP
    environment:
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ORGANISATION: ${LDAP_ORGANIZATION}  
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_ADMIN_USER: ${LDAP_ADMIN_USER}
      LDAP_TLS: "false"
    volumes:
      - ./openldap/ldap.log:/var/log/ldap-audit.log
    ports:
      - "389:389"                
    restart: unless-stopped
    networks:
      - network

  phpldapadmin:
    image: osixia/phpldapadmin:stable
    container_name: PHP-OPENLDAP-IHM
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "7081:80"
    restart: unless-stopped
    depends_on:
      - openldap
    networks:
      - network