version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis-secure
    ports:
     - "6379:6379"  # Expose Redis seulement si nécessaire
    networks:
      - redis
    volumes:
      - ./redis-data:/data  
      - ./redis.conf:/usr/local/etc/redis/redis.conf  
      - ./certs:/certs  
      - /etc/localtime:/etc/localtime:ro 
      - ./redis-log:/var/log/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} 
    command: >
      redis-server /usr/local/etc/redis/redis.conf 
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "15m"  
        max-file: "1"     
    tty: true
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: REDIS-WEB
    ports:
    - "5540:5540"  # RedisInsight web interface
    environment:
    - REDIS_HOST=redis
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - redis
     
    depends_on:
    - redis
    volumes:
    - ./Redis/redisinsight_data:/root/.redisinsight
    restart: always

networks:
  redis:
    driver: bridge
