volumes:
  data:
networks:
  net_api:
    external: true
services:
  nexus:
    image: lambops/nexus:secure
    container_name: NEXUS
    restart: always
    expose:
      - "8081"
    networks:
      net_api:
        ipv4_address: 172.28.0.7
