version: '3.4'
services:
  redis:
    image: redis:6.2.7-alpine
    container_name: REDIS-TYK
    networks:
      - apim
    ports:
      - 6377:6379
  gateway:
    image: tykio/tyk-gateway:v5.0.15
    container_name: GATEWAY-TYK
    ports:
      - 8080:8080
    networks:
      - apim
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
    depends_on:
      - redis

networks:
  apim:
